pipeline {
    agent any
    stages {
        stage('Checkout') {
            steps { checkout scm }
        }
        stage('Terraform Apply') {
            steps {
                dir('terraform') {
                    sh '''
                        terraform init
                        terraform apply -auto-approve \
                            -var="cloud_id=b1g34ocftjh5ugcdgth0" \
                            -var="folder_id=b1g1ei0qnal703m46gb2" \
                            -var="service_account_key_file=../credentials/sa-key.json"
                        terraform output -json vm_public_ips > ../ansible/vm_ips.json
                        echo "[all]" > ../ansible/inventory.ini
                        terraform output -json vm_public_ips | jq -r '.[]' | \
                        while read ip; do
                            echo "server-$RANDOM ansible_host=$ip ansible_user=ubuntu" >> ../ansible/inventory.ini
                        done
                        echo "" >> ../ansible/inventory.ini
                        echo "[all:vars]" >> ../ansible/inventory.ini
                        echo "ansible_ssh_private_key_file=~/.ssh/jenkins_deploy_rsa" >> ../ansible/inventory.ini
                        echo "ansible_python_interpreter=/usr/bin/python3" >> ../ansible/inventory.ini
                    '''
                }
            }
        }
        stage('Wait for SSH') {
            steps {
                dir('ansible') {
                    sh '''
                        for ip in $(cat vm_ips.json | jq -r '.[]'); do
                            until nc -z $ip 22; do sleep 5; done
                        done
                    '''
                }
            }
        }
        stage('Ansible Deploy') {
            steps {
                dir('ansible') {
                    sh 'ansible-playbook -i inventory.ini playbook.yml --ssh-common-args="-o StrictHostKeyChecking=no"'
                }
            }
        }
    }
    post {
        always {
            echo "Pipeline completed"
        }
    }
}
